### ISSUE TITLE
Better configuration management

### ISSUE THREAD

**Issue by thomasstevens89** [chefsplate/laravel-doctrine-odm#4]
https://github.com/chefsplate/laravel-doctrine-odm/blob/8477d74cae1feea821090de1ef953c1a4601d023/src/Providers/DocumentMapperServiceProvider.php#L52-L53

The above code only supports passing the DSN to the ODM MongoDB Connection so its not currently possible to specify connection or driver level options such as `connectRetry` which is important for handling a primary to secondary failover more gracefully.

**Comment by thomasstevens89** [comment]
Update: we will refactor how configuration is defined from driver level up to the ODM wrapper to address a number of opportunities for a more flexible setup

**Comment by davidchchang** [comment]
Closing with merge of PR. We can revisit when further configuration options are desired. Thanks again, Thomas!
